apiVersion: v1
kind: Service
metadata:
  name: quickpeek-service
spec:
  selector:
    app: quickpeek-app
  ports:
    - protocol: TCP
      port: 80  # The port on which the service is exposed
      targetPort: 3000  # The port your app is listening on inside the container
  type: LoadBalancer  # Change to NodePort if you don't want to expose it outside the cluster